---
- name: Block IP Attacker
  hosts: check_point
  connection: httpapi
  tasks:
    - name: Register IP Attacker
      cp_mgmt_host:
        name: "zimbra_attacker"
        ip_address: "10.8.230.110"
        state: present
        auto_publish_session: true

    - name: Create blacklist entry
      checkpoint_access_rule:
        auto_install_policy: yes
        auto_publish_session: yes
        layer: Network
        position: top
        name: "blacklist_policy"
        source: "zimbra_attacker"
        destination: "IP_Ext_Zimbra_10.8.150.64"
        action: drop

    - name: publish
      cp_mgmt_publish:
